### PR TITLE
perf: replace chalk with picocolors

### PR DESCRIPTION
**Pull request by Simon-He95**
[picocolors](https://github.com/alexeyraspopov/picocolors) have better performance

### CODE REVIEW

**Comment by robbe-luo** [comment]
@Simon-He95 please give us some reports.

**Comment by Simon-He95** [comment]
> @Simon-He95 please give us some reports.

link: https://github.com/alexeyraspopov/picocolors

picocolors use Benchmarks to compare with chalk

image

**Review by NiuZhuang — COMMENTED** [review]
Hi Simon,

Thank you for your kind pull request.

Since `picocolors` has not been updated in two years, while `chalk` is much more actively developed, I prefer to maintain the status quo.

Best regards.

**Comment by Simon-He95** [comment]
Well, my personal understanding is that excessive encapsulation of chalk leads to problems such as performance and huge code. In vite, chalk has been replaced by picocolors, a more future-proof ES syntax

**Pull request closed without merging**
